version: "2.1"

services:
  docksal-vhost-proxy:
    container_name: docksal-vhost-proxy
    image: ${IMAGE_VHOST_PROXY:-docksal/vhost-proxy:1.2}
    entrypoint: hostname

  docksal-dns:
    container_name: docksal-dns
    image: ${IMAGE_DNS:-docksal/dns:1.0}
    entrypoint: hostname

  docksal-ssh-agent:
    container_name: docksal-ssh-agent
    image: ${IMAGE_SSH_AGENT:-docksal/ssh-agent:1.0}
    entrypoint: hostname

  docksal-web:
    container_name: docksal-web
    image: ${IMAGE_WEB:-docksal/web:2.1-apache2.4}
    entrypoint: hostname

  docksal-db:
    container_name: docksal-db
    image: ${IMAGE_DB:-docksal/db:1.2-mysql-5.6}
    entrypoint: hostname

  docksal-cli:
    container_name: docksal-cli
    image: ${IMAGE_CLI:-docksal/cli:2.2-php7.1}
    entrypoint: hostname

  docksal-installer:
    container_name: docksal-installer
    image: franela/dind
    volumes:
      - /bin:/bin
      - /dev:/dev
      - /etc:/etc
      - /home:/home
      - /lib:/lib
      - /media:/media
      - /mnt:/mnt
      - /opt:/opt
      #- /proc:/proc
      - /root:/root
      - /run:/run
      - /sbin:/sbin
      - /srv:/srv
      - /sys:/sys
      - /tmp:/tmp
      - /usr:/usr
      - /var:/var
    command: "sh -c '(apk add --update bash curl sudo git); (curl -fsSL https://get.docksal.io | CI=true bash)'"
    privileged: true
